### ISSUE TITLE
Resolver Width e Height geral

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Cubinho#26]
o nosso Width e Height esta gambiarrado, o tamanho da tela pode ser diferente do numero de colunas no mapa e o nosso esta setado para ser o mesmo, isso precisa ser atualizado.

**Comment by Jerfin97** [comment]
Resolvido ne?

**Comment by SaltyGum** [comment]
file:///home/saltygum/Ãrea de trabalho/gandalf-sax-guy.gif

**Comment by Jerfin97** [comment]
![gandalf](https://user-images.githubusercontent.com/70494815/232319715-517b1d68-bf8d-498d-af72-79f61caa318e.gif)
