### ISSUE TITLE
Mapa maior que a tela buga tudo

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Cubinho#38]
![image](https://user-images.githubusercontent.com/21111088/232334991-91cba1d4-3782-4eda-91f2-faf8f9d35755.png)
Se o mapa for gigante e maior que a tela, fica bugado, precisa ver essa situa'c~ao.

**Comment by dvargas1** [comment]
Se passar em numero de linhas tambem, seg fault no rosto, de alguima forma ele precisa ficar contido em um espaco da tela, ou agnt giva o minimapa, e uma possibilidade.

**Comment by Jerfin97** [comment]
e por ser maior que a tela ou por nao conseguir carregar tudo ?

**Comment by Jerfin97** [comment]
```
EA ./maps/HEDGE_1A.xpm
SO ./maps/uniao.xpm
NO ./maps/BRICK_3D.xpm
WE ./maps/HEDGE_1B.xpm

F 128,96,67
C 0,181,226

111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
100N00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111
```

**Comment by Jerfin97** [comment]
Fiz um teste com esse mapa e nao deu crash dani vc arrumou ?
Ele so fica renderizando por cima do anterior no caso o final fica no meio ai parece que vc atravessa e volta.
![image](https://user-images.githubusercontent.com/70494815/232528056-18907b91-f9cc-406f-9d35-0af313500ec9.png)

**Comment by Jerfin97** [comment]
Uma solucao que ia ficar maneira seria o mapa andar com o player reproducao centrada no player no caso o mapa se move e nao o player tipo radar saca

**Comment by Jerfin97** [comment]
![image](https://user-images.githubusercontent.com/70494815/232529274-a52b8054-3e4e-490b-81ff-23a5e3537fcf.png)

**Comment by dvargas1** [comment]
O outro teste que deu segfault foi com uma quantidade grande de linhas, ele acabou ocupando a tela inteira e imagino que por isso deu segfault

**Comment by Jerfin97** [comment]
Acho que se fizer o mapa assim resolve os dois problemas

**Comment by Jerfin97** [comment]
O segfault deve vir de tentar escrever fora da tela

**Comment by dvargas1** [comment]
acho que encontrar uma forma de escalar o minimapa é mais facil mas radar tbm é uma possibilidade, só acho que renderizar com a referencia do jogador, vai ser um segundo projeto.

**Comment by Jerfin97** [comment]
Acho que a ideia seria mais fazer o mapa andar saca ? ele escala com distancia baseada no player

**Comment by Jerfin97** [comment]
sla uns 300 pixels de distancia do player .

**Comment by Jerfin97** [comment]
Mas se ficar muito ruim a gente dropa

**Comment by dvargas1** [comment]
discord, conversar na issue nao da
