### ISSUE TITLE
Ideia, adicionar mapas com erro para testes especificos.

### ISSUE THREAD

**Issue by dvargas1** [Jerfin97/Cubinho#9]
Criar talvez um pequeno script de testes para validacao de mapa, vale a pena ?

**Comment by Jerfin97** [comment]
Esta aceitando algumas coisas erradas exemplo

1111101
100E0000000000000001
11111

esse mapa foi aceito

11111
100E0000000000000001
11111

esse tambem acho que nao deveria

**Comment by Jerfin97** [comment]
Ele esta aceitando as coisas fora de ordem o que e bom demais
Exemplo do teste 
```
NO ./maps/BRICK_3D.xpm




SO ./maps/uniao.xpm





WE ./maps/HEDGE_1B.xpm





F 20,22,25




C 20,11,20

EA ./maps/HEDGE_1A.xpm

1111101
100E0000000000000001
11111


```
